service: arithmetic-calculator-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  deploymentMethod: direct
  stage: ${opt:stage, 'dev'}
  apiGateway:
    request:
      schemas:
        ${file(./api/schema-definitions.yml)}

plugins:
  # Needed for Python requirements packaging
  - serverless-python-requirements
  # Stores CloudFormation and Serverless stack output to a file
  - serverless-stack-output
  # Provides API Gateway throttling configuration for this service
  - serverless-api-gateway-throttling

custom:
  pythonRequirements:
    layer: true
    useDownloadCache: false
    useStaticCache: false
  defaultCallBackURL:
    dev: "http://localhost:8080/callback"
    prod: "http://example.com/callback" # TODO CHANGE ME BEFORE DEPLOY TO PRODUCTION
  defaultSignOutURL:
    dev: "http://localhost:8080/logout"
    prod: "http://example.com/logout" # TODO CHANGE ME BEFORE DEPLOY TO PRODUCTION
  callBackUrls:
    dev:
      - ${self:custom.defaultCallBackURL.dev}
    prod:
      - ${self:custom.defaultCallBackURL.prod}
  signOutURLs:
    dev:
      - ${self:custom.defaultSignOutURL.dev}
    prod:
      - ${self:custom.defaultSignOutURL.prod}
  tableName: ${self:service}-${opt:stage, self:provider.stage}-ArithmeticCalculatorTable
  output:
    handler: scripts/output.handler
    file: env.json
  # Default throttling for all API Gateway endpoints on this service
  apiGatewayThrottling:
    maxRequestsPerSecond: ${self:custom.maxRequests.${opt:stage, self:provider.stage}}
    maxConcurrentRequests: ${self:custom.maxConcurrency.${opt:stage, self:provider.stage}}
  maxRequests:
    dev: 5
    prod: 10
  maxConcurrency:
    dev: 50
    prod: 100

package:
  individually: true  # Package each function individually
  patterns:  # Excluding some folders during function packaging
    - "!node_modules/**"
    - "!scripts/**"
    - "!.tox/**"
    - "!tox.ini"
    - "!**/.coverage"
    - "!**/__pycache__/**"
    - "!**/env/**"
    - "!**/.env/**"
    - "!**/tests/**"
    - "!regression/**"
    - "!schema_validators/**"
    - "!.serverless/**"
    - "!.github/**"
    - "!.env/**"
    - "!env.json"
    - "!README.md"
    - "!ArithmeticCalculatorArchitectureDiagram.png"
    - "!package.json"
    - "!package-lock.json"
    - "!resources.yml"
    - "!api/**"


functions:
  NewOperation:
    handler: lambdas.new_operation.main.handler
    memorySize: 256
    layers:
      - Ref: PythonRequirementsLambdaLayer
    environment: ${file(./lambdas/new_operation/env.yml):${opt:stage, self:provider.stage}}
    role:
       Fn::GetAtt:
        - NewOperationLambdaRole
        - Arn
    events:
      - http:
          path: /new-operation
          method: post
          request:
            schemas:
              application/json: new-operation-model

  GetBalance:
    handler: lambdas.get_balance.main.handler
    memorySize: 256
    layers:
      - Ref: PythonRequirementsLambdaLayer
    environment: ${file(./lambdas/get_balance/env.yml):${opt:stage, self:provider.stage}}
    role:
       Fn::GetAtt:
        - GetBalanceLambdaRole
        - Arn
    events:
      - http:
          path: /get-balance
          method: get

  PollResults:
    handler: lambdas.poll_results.main.handler
    memorySize: 256
    layers:
      - Ref: PythonRequirementsLambdaLayer
    environment: ${file(./lambdas/poll_results/env.yml):${opt:stage, self:provider.stage}}
    role:
       Fn::GetAtt:
        - PollResultsLambdaRole
        - Arn
    events:
      - http:
          path: /poll-results/{record_id}
          method: get
          request:
            parameters:
              paths:
                record_id: true

  ArithmeticOperationWorker:
    handler: lambdas.arithmetic_operation_worker.main.handler
    memorySize: 512
    layers:
      - Ref: PythonRequirementsLambdaLayer
    environment: ${file(./lambdas/arithmetic_operation_worker/env.yml):${opt:stage, self:provider.stage}}
    role:
       Fn::GetAtt:
        - ArithmeticOperationWorkerLambdaRole
        - Arn
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ArithmeticOperationQueue
              - Arn

  HealthCheck:
    handler: healthcheck.hello
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          path: /healthcheck
          method: get

resources:
  ${file(./resources.yml)}
